### ISSUE TITLE
Could lib.recursiveUpdate be used for (∧)?

### ISSUE THREAD

**Issue by 8573** [dhall-lang/dhall-nix#1]
Reading the part of the blog post [Typed Nix programming using Dhall]
on how Dhall's (∧) operator is translated to Nix, I wondered whether
it could use the Nix standard library function [`lib.recursiveUpdate`]
— or `(lib.flip lib.recursiveUpdate)`, as it looks to me like the
generated code has the first argument's key-value pairs override those
of the second argument (where they aren't sets to recursively merge),
whereas `lib.recursiveUpdate` gives precedence to the second argument.

[Typed Nix programming using Dhall]: <http://www.haskellforall.com/2017/01/typed-nix-programming-using-dhall.html>
[`lib.recursiveUpdate`]: <https://github.com/NixOS/nixpkgs/blob/master/lib/attrsets.nix#L394-L416>

**Comment by Gabriella439** [comment]
Yeah, I can definitely fix it to match the precedence of `lib.recursiveUpdate`.  I still prefer to implement it inline mainly because I don't want the generated code to depend on `<nixpkgs>`
