### ISSUE TITLE
`hnix-0.5.2` incompatible with `dhall-1.18.0`

### ISSUE THREAD

**Issue by Gabriella439** [dhall-lang/dhall-nix#17]
`hnix-0.5.2` has an upper bound of `megaparsec < 0.7.0`, whereas `dhall-1.18.0` has a lower bound of `0.7.0 <= megaparsec`

This means that we need to fix https://github.com/haskell-nix/hnix/issues/368 before we can cut a new release of `dhall-nix` that is compatible with `dhall-1.18.0`

**Comment by dhess** [comment]
`hnix-0.6.0` has been released and uses `megaparsec-0.7`. Are there plans to update `dhall-nix` to the latest `dhall` in the near future?

**Comment by Gabriella439** [comment]
@dhess: Yes, definitely.  I've been dying to cut a new release of `dhall-nix` once `hnix` supported a recent `megaparsec`

**Comment by dhess** [comment]
OK, great news! I'm starting to use `dhall-nix` in my devops pipelines, and I'm happy to hear that it'll be around in the future!

**Comment by Gabriella439** [comment]
I'm closing out issues because I'm migrating `dhall-nix` as a sub-project of the `dhall-haskell` project and archiving this project.

So this is pretty close to being Hackage-ready.  `dhall-nix` now builds against the latest `dhall`, but it requires a version of `hnix` from GitHub since there are still issues with the latest `hnix` on Hackage.  Once `hnix` is readdy on Hackage then I'll upload a new `dhall-nix` release, which should fix this.  In the meantime, though, I do plan to at least publish the `dhall-nix` binaries built by CI with each release which you can use in your pipelines.
