### ISSUE TITLE
Update to newest dhall (& hnix)

### ISSUE THREAD

**Issue by Profpatsch** [dhall-lang/dhall-nix#18]
There have been a few changes with dhall (multiple `let` bindings, `Some/None` and the new `Map` module).

`hnix` got a new major version release a few days ago, but for now I’ll update to the older one.

Please assign me to this issue.

**Comment by Gabriella439** [comment]
I'm also going to merge this repository into the `dhall-haskell` repository now that this builds against the latest version of `dhall`
