### ISSUE TITLE
Using relative path to a "type" file in dhallToNix

### ISSUE THREAD

**Issue by barakber** [dhall-lang/dhall-nix#2]
First of all, thanks for the great work :+1:.  
In our company we're working on building a directory tree structure of Dhall "type" files to model parts of NixOS/NixOPS.  
For example - NixOS services like https://github.com/NixOS/nixpkgs/blob/6bc889205a285859078f53959a833459d2371d9a/nixos/modules/services/networking/ssh/sshd.nix#L65 or NixOPS cloud infrastructures like https://github.com/NixOS/nixops/blob/3f516086008f2896e5e657bd2a9dd6058db0bd61/nix/azure.nix#L142.  
  
During this work we've hit an issue with embedding Dhall in Nix (using `dhallToNix`) that I'm not sure how to solve - how should we apply a type-file, from somewhere else in our project tree? Here's an example -  
```nix
let
  pkgs = import <nixpkgs> { };
  inherit (pkgs) dhallToNix;

in
  { vbox = (dhallToNix "{ headless = True, vcpu = +2 } : ../../../ops/VirtualBox.dhall");
  }
```  
This code fails since `../../../ops/VirtualBox.dhall` is not copied by Nix as part of the "current" derivation, and is not available for `dhallToNix` when it runs.  
We've tried several hacks around this as well, but couldn't come up with a nice way to really leverage types (using Dhall) in our Nix codebase.

**Comment by Gabriella439** [comment]
Yeah, I have ran into this issue myself.  One way to address this problem is to interpolate the relative path to the Dhall expression, like this:

```nix
let
  pkgs = import <nixpkgs> { };
  inherit (pkgs) dhallToNix;

in
  { vbox = (dhallToNix "{ headless = True, vcpu = +2 } : ${../../../ops/VirtualBox.dhall}");
  }
```

That will then ensure that Nix adds `../../../ops/VirtualBox.dhall` to the `/nix/store` as some `/nix/store/....-VirtualBox.dhall` path and Nix will then interpolate path that into the string giving you the following final Dhall expression

```haskell
{ headless = True, vcpu = +2 } : /nix/store/...-VirtualBox.dhall
```

The other benefit of doing this is that Nix will then correctly detect that the `VirtualBox.dhall` file is a build-time dependency of the Dhall expression, ensuring that the import will be present on any machine that evaluates that Dhall expression.

**Comment by barakber** [comment]
Thanks. Our problem is that the `../../ops/VirtualBox.dhall` file also uses many other type-files in other places in the directory tree. Will this trick work for an entire directory tree?

**Comment by Gabriella439** [comment]
Oh, I see the issue.  So if all of the Dhall expressions are located within a single subdirectory (such as `../../../ops`) and they all reference each other by relative paths then you can do this instead:

```nix
let
  pkgs = import <nixpkgs> { };
  inherit (pkgs) dhallToNix;

in
  { vbox = (dhallToNix "{ headless = True, vcpu = +2 } : ${../../../ops}/VirtualBox.dhall");
  }
```

Then the entire `../../../ops` directory will be copied to the `/nix/store` and the `VirtualBox.dhall` dependency will be replaced with an absolute path within that directory.  Every transitive dependency of `VirtualBox.dhall` should be correctly referenced via relative paths.

**Comment by barakber** [comment]
Thanks! works great!

**Comment by Gabriella439** [comment]
You're welcome! :)
